version: "3"

networks:
  common:

services:
  nginx:
    image: nginx:latest
    networks:
      - common
    depends_on:
      - web
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./build/app/static:/app/static:ro
    ports:
      - "3434:80"

  web:
    build:
      context: ./build/
    networks:
      - common
    depends_on:
      - db


  db:
    image: postgres
    networks:
      - common
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: q1w2e3r4
      POSTGRES_DB: dps
